backend:
    name: git-gateway
    branch: main
    repo: peterjlambert/petelambert.com
display_url: https://petelambert.com
media_folder: public/assets
public_folder: /assets
collections:
  - name: Journal
    label: journal
    folder: src/journal
    slug: {{year}}-{{month}}-{{day}}-{{slug}}
    create: true
    delete: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: "date", widget: "datetime", default: {{year}}-{{month}}-{{day}}}
      - {label: "Tags", name: "keywords", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
