backend:
  name: git-gateway
  branch: latest
  repo: peterjlambert/petelambert.com
display_url: https://petelambert.com
media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - name: journal
    label: Journal
    folder: src/journal
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    delete: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          default: '{{year}}-{{month}}-{{day}}',
        }
      - { label: 'Tags', name: 'keywords', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'markdown' }
      - { label: 'Category', name: 'tags', widget: 'hidden', default: 'post' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'src/index.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Keywords,
              name: keywords,
              widget: list,
              default:
                [
                  pete lambert,
                  designer,
                  design manager,
                  design engineer,
                  musician,
                  guitarist,
                  web designer,
                  engineer,
                  web,
                  ui,
                  yorkshire,
                  web developer,
                  music,
                ],
            }
          - { label: Slug, name: slug, widget: string, default: 'home' }
          - { label: Body, name: body, widget: markdown }
      - label: 'Contact'
        name: 'contact'
        file: 'src/contact.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Keywords,
              name: keywords,
              widget: list,
              default:
                [
                  pete lambert,
                  designer,
                  design manager,
                  design engineer,
                  musician,
                  guitarist,
                  web designer,
                  engineer,
                  web,
                  ui,
                  yorkshire,
                  web developer,
                  music,
                ],
            }
          - { label: Body, name: body, widget: markdown }
      - label: 'Credits'
        name: 'credits'
        file: 'src/credits.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Keywords,
              name: keywords,
              widget: list,
              default:
                [
                  pete lambert,
                  designer,
                  design manager,
                  design engineer,
                  musician,
                  guitarist,
                  web designer,
                  engineer,
                  web,
                  ui,
                  yorkshire,
                  web developer,
                  music,
                ],
            }
          - { label: Body, name: body, widget: markdown }
